ahoyapi: v2
usage: CLI utilities
commands:

  build:
    cmd: |
      php ./bin/satis build ./package-mirror.json ./package-mirror

  server:
    cmd: |
      php -S localhost:4680 -t ./package-mirror
