ahoyapi: v2
usage: CLI utilities
commands:

  satis:
    cmd: |
      docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis "$@"

  satis-build:
    usage: ahoy satis packages.json build-dir
    cmd: |
      docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis build -vvv "$1" /build/"$2"
      docker run --rm --init -it \
        --volume $(pwd):/build \
        composer/satis /build/branding.sh "/build/$2/index.html"

  build:
    cmd: |
      ahoy satis-build satis-govcms-beta8.json app

  build-beta7:
    cmd: |
      ahoy satis-build satis-govcms-beta7.json app/beta7

  build-edge:
    cmd: |
      ahoy satis-build satis-govcms-edge.json app/edge

  build-whitelist:
    cmd: |
      ahoy satis-build satis-govcms-whitelist.json app/whitelist

  build-extras:
    cmd: |
      ahoy satis-build satis-govcms-extras.json app/extras
