ahoyapi: v2
usage: CLI utilities
commands:

  build:
    cmd: |
      #php ./bin/satis -vvv build ./satis-govcms-dev.json ./app/dev
      #php ./bin/satis -vvv build ./satis-govcms-beta5.json ./app/beta5
      #php ./bin/satis -vvv build ./satis-govcms-beta6.json ./app/beta6
      php ./bin/satis -vvv build ./satis-govcms-beta7.json ./app/beta7
      php ./bin/satis -vvv build ./satis-govcms-beta8.json ./app/beta8
      php ./bin/satis -vvv build ./satis-govcms-beta8.json ./app
      ahoy changelog
  server:
    cmd: |
      php -S localhost:4680 -t ./app

  changelog:
    cmd: |
      git diff app/index.html | grep "^+" | egrep -o 'https?://[^ ]+'