ahoyapi: v2
usage: CLI utilities
commands:

  satis:
    usage: ahoy satis ARGS
    cmd: |
      docker run --rm --init -it \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis "$@"

  satis-build:
    usage: ahoy satis packages.json build-dir
    cmd: |
      docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis build -vvv "$1" /build/"$2"
      docker run --rm --init -it \
        --volume $(pwd):/build \
        composer/satis /build/branding/branding.sh "/build/$2"

  build-all-production:
    cmd: |
      ahoy build-stable
      ahoy build-master
      ahoy build-develop
      ahoy build-whitelist

  build-stable:
    cmd: |
      ahoy satis-build satis-config/govcms-stable.json app

  build-master:
    cmd: |
      ahoy satis-build satis-config/govcms-master.json app/master

  build-develop:
    cmd: |
      ahoy satis-build satis-config/govcms-develop.json app/develop

  build-whitelist:
    cmd: |
      ahoy satis-build satis-config/govcms-whitelist.json app/whitelist

  build-security-updates:
    cmd: |
      ahoy satis-build satis-config/govcms-security_updates.json app/security_update

  server:
    cmd: |
      PHP -S localhost:4686 -t app
