ahoyapi: v2
usage: CLI utilities
commands:

  satis:
    usage: ahoy satis packages.json build-dir
    cmd: |
      docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis build -vvv "$1" /build/"$2"
      docker run --rm --init -it \
        --volume $(pwd):/build \
        composer/satis /build/branding.sh "/build/$2/index.html"

  build-production:
    cmd: |
      LATEST=satis-govcms-beta9.json
      ahoy satis "$LATEST" app
      ahoy build-whitelist

  build-whitelist:
    cmd: |
      ahoy satis satis-govcms-whitelist.json app/whitelist

  # Below are experimental. Do not deploy to production.

  build-beta7:
    cmd: |
      ahoy satis satis-govcms-beta7.json app/beta7

  build-beta8:
    cmd: |
      ahoy satis satis-govcms-beta8.json app/beta8

  build-edge:
    cmd: |
      ahoy satis satis-govcms-edge.json app/edge

  build-extras:
    cmd: |
      ahoy satis satis-govcms-extras.json app/extras

  # This is temporary until the lagoon/govcms scaffold is on packagist.
  build-projects:
    cmd: |
      ahoy satis satis-govcms-projects.json app/projects
