ahoyapi: v2
usage: CLI utilities
commands:

  build-beta8:
    cmd: |
      php ./bin/satis build ./satis-govcms-beta8.json ./app
      php ./bin/satis build ./satis-govcms-beta8.json ./app/beta8

  build-edge:
    cmd: |
      php ./bin/satis build ./satis-govcms-edge.json ./app/edge

  build-whitelist:
    cmd: |
      php ./bin/satis -vvv build ./satis-govcms-whitelist.json ./app/whitelist

  build-extras-webform:
    cmd: |
      php ./bin/satis -vvv build ./satis-govcms-extras-webform.json ./app/extras/webform

  server:
    cmd: |
      php -S localhost:4680 -t ./app

  changelog:
    cmd: |
      git diff app/index.html | grep "^+" | egrep -o 'https?://[^ ]+'
