ahoyapi: v2
usage: CLI utilities
commands:

  satis:
    usage: Execute composer/satis via docker.
    cmd: |
      docker run --rm --init -it \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis "$@"

  satis-build:
    usage: Execute composer/satis passing in a json and a build dir.
    cmd: |
      docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis build -vvv "$1" /build/"$2"
      docker run --rm --init -it \
        --volume $(pwd):/build \
        composer/satis /build/scripts/branding.sh "/build/$2"

  build:
    usage: Build the satis package lists - use {stable|master|develop} to target a branch.
    cmd: |
      if [ "$1" == "stable" ] || [ -z "$1" ]; then
        echo -e "\033[1;35m--> Building govcms-stable.json  \033[0m"
        ahoy satis-build satis-config/govcms-stable.json app
      else
        echo -e "\033[1;35m--> Building govcms-"$1".json  \033[0m"
        ahoy satis-build satis-config/govcms-"$1".json app/"$1"
      fi

  build-all:
    usage: Build all satis package lists
    cmd: |
      ahoy build-stable
      ahoy build-master
      ahoy build-develop
      ahoy build-whitelist

  build-whitelist:
    usage: Build satis.govcms.gov.au/whitelist
    cmd: |
      ahoy satis-build satis-config/govcms-whitelist.json app/whitelist

  check-dupes:
    usage: Check for duplicate packages - use {stable|master|develop} to target a branch.
    cmd: |
      if [ "$1" == "stable" ] || [ -z "$1" ]; then
        SATIS_BUILD=app ./scripts/check-dupes.sh
      else
        SATIS_BUILD=app ./scripts/check-dupes.sh "$@"
      fi

  check-dupes-all:
    usage: Check for duplicate packages in all branches.
    cmd: |
      ahoy check-dupes stable
      ahoy check-dupes master
      ahoy check-dupes develop

  verify:
    usage: Verify the satis resolves - use {stable|master|develop} to target a branch.
    cmd: |
      if [ "$1" == "stable" ] || [ -z "$1" ]; then
        SATIS_BUILD=app ./scripts/verify.sh
      else
        SATIS_BUILD=app ./scripts/verify.sh "$@"
      fi

  verify-all:
    usage: Verify the satis resolves for all branches.
    cmd: |
      ahoy verify stable
      ahoy verify master
      ahoy verify develop

  debug:
    usage: Get clear information about satis issues - use {stable|master|develop} to target a branch.
    cmd: |
      if [ "$1" == "stable" ] || [ -z "$1" ]; then
        SATIS_BUILD=app ./scripts/check-missing.sh
        ahoy check-dupes stable
      else
        SATIS_BUILD=app ./scripts/check-missing.sh "$@"
        ahoy check-dupes "$@"
      fi

  debug-all:
    usage: Get clear information about satis issues for all branches.
    cmd: |
      ahoy debug stable
      ahoy debug master
      ahoy debug develop

  server:
    usage: Make satis available on localhost:4142
    cmd: |
      PHP -S localhost:4143 -t app
