---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

test:

  stage: test

  script:
    - composer create-project --stability dev --prefer-dist govcms/govcms8-project build-test

before_script:
  - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
