---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

test:

  stage: test

  script:
    - mkdir -p workspace
    - |
      set +exuo pipefail # Installing govcms from our satis.
      git clone https://github.com/govCMS/govcms8-scaffold-paas workspace
      cd workspace
      git checkout master
      composer config secure-http false
      cat composer.json \
        | jq .repositories='{"govcms":{"type":"composer","url":"http://localhost:4680"},"packagist.org":false}' \
        | tee composer.json
      composer update

before_script:
  - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
