---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

test:

  stage: test

  script:
    - |
      set -x # Installing govcms using ONLY our satis.
      cd workspace
      git checkout master
      cat composer.json
      composer config secure-http false # Only needed to point to local satis.
      # Simulate locked composer.
      cat composer.json
      cat composer.json \
        | jq .repositories='{"govcms":{"type":"composer","url":"http://localhost:4680"},"packagist.org":false}' \
        | tee composer.json
      cat composer.json
      composer update
      composer validate
    - |
      set -x # Build the drupals.
      export DOCKER_HOST=tcp://localhost:2375
      docker network prune -f && docker network create amazeeio-network
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io
      docker-compose up -d mariadb
      docker-compose up -d cli
      docker-compose ps
      docker-compose config
      docker-compose exec -T cli drush si -y govcms
    - |
      set -x # Test the drupals
      docker-compose exec -T cli drush status
    - |
      set -x # Can't update existing module.
      set +e
      ERR=1 && composer require drupal/redirect 1.x-dev || ERR=$?
      set -e
      if [ "$ERR" -eq 0 ]; then echo "Correctly fails to install dev version redirect." && exit 1; fi
    - |
      set -x # Can't update undesireable version.
      set +e
      ERR=1 && composer require drupal/bad_judgement || ERR=$?
      set -e
      if [ "$ERR" -eq 0 ]; then echo "Correctly fails add bad judgement." && exit 1; fi
    - |
      # If a package appears many times, then something is wrong with the configuration.
      which jq
      for f in app/include/*.json
      do
        echo "$f"
        # Flatten the packagist json to just name, and count the number of each ".name" (eg drupal/core).
        TOOMANY=$(cat "$f" jq '.packages | [.[] ] | .[] | [.[]] | .[] | .name' | sort | uniq -c | awk '{if($1>2)print$2}')
        if [[ ! -z $OUTPUT ]]; then echo "Two many packages for $TOOMANY" && exit 1; fi
      done

before_script:
  - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
  - mkdir -p workspace
  - git clone --depth 1 --branch master https://github.com/govCMS/govcms8-scaffold-paas workspace
