---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

test:

  stage: test

  script:
    - docker-compose up -d
    - curl -l0 http://nginx:8080

before_script:
  - docker network prune -f && docker network create amazeeio-network
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
