---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

test:

  stage: test

  script:
    - |
      set +exuo pipefail # Installing govcms using ONLY our satis.
      cd workspace
      git checkout master
      composer config secure-http false # Only needed to point to local satis.
      # Simulate locked composer.
      cat composer.json \
        | jq .repositories='{"govcms":{"type":"composer","url":"http://localhost:4680"},"packagist.org":false}' \
        | tee composer.json
      composer validate
      composer update
    - |
      set +exuo pipefail # Build the drupals.
      export DOCKER_HOST=tcp://localhost:2375
      docker network prune -f && docker network create amazeeio-network
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io
      docker-compose up -d mariadb
      docker-compose up -d cli
      docker-compose ps
      docker-compose config
      docker-compose exec -T cli drush si -y govcms
    - |
      set +exuo pipefail # Test the drupals
      docker-compose exec -T cli drush status

before_script:
  - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
  - mkdir -p workspace
  - git clone https://github.com/govCMS/govcms8-scaffold-paas workspace
