---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

default:

  stage: test

  script:
    - |
      # If a package appears many times, then something is wrong with the configuration.
      for f in app/include/*.json
      do
        # Flatten the packagist json to just name, and count the number of each ".name" (eg drupal/core).
        # This would test if any has more than 123 packages: ($1>123). (@todo use an awk variable)
        TOOMANY=$(cat "$f" | jq '.packages | [.[] ] | .[] | [.[]] | .[] | .name' | sort | uniq -c | awk '{if($1>2)print$2}')
        if [[ ! -z $OUTPUT ]]; then echo "Two many packages for $TOOMANY" && exit 1; fi
      done
      echo "No package has too many versions."
    - |
      set -x # Installing govcms using ONLY our satis.
      cd workspace
      git checkout master
      composer config secure-http false # Only needed to point to local satis.
      # Simulate locked composer.
      cat composer.json | jq '.repositories'
      cat composer.json \
        | jq .repositories='{"govcms":{"type":"composer","url":"http://localhost:4680"},"packagist.org":false}' \
        | tee composer.json
      [ -s composer.json ] && echo "Why are you empty (Si debugging)."
      composer update
      composer validate
    - |
      set -x # Build the drupals.
      docker network prune -f && docker network create amazeeio-network
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io
      docker-compose config
      docker-compose up -d mariadb
      docker-compose up -d cli
      docker-compose ps
      docker-compose exec -T cli drush si -y govcms
    - |
      set -x # Test the drupals
      docker-compose exec -T cli drush status
    - |
      set -x # Test that we can't update existing module.
      set +e
      ERR=1 && composer require drupal/redirect 1.x-dev || ERR=$?
      set -e
      if [ "$ERR" -eq 0 ]; then echo "Correctly fails to install dev version redirect." && exit 1; fi
    - |
      set -x # Test that we can't update to undesireable package versions.
      set +e
      ERR=1 && composer require drupal/bad_judgement || ERR=$?
      set -e
      if [ "$ERR" -eq 0 ]; then echo "Correctly fails add bad judgement." && exit 1; fi

whitelist:

  stage: test

  # These are essentially duplications of the default tests. No comments. Pre-abstraction.
  script:
    - |
      for f in app/whitelist/include/*.json
      do
        TOOMANY=$(cat "$f" | jq '.packages | [.[] ] | .[] | [.[]] | .[] | .name' | sort | uniq -c | awk '{if($1>2)print$2}')
        if [[ ! -z $OUTPUT ]]; then echo "Two many packages for $TOOMANY" && exit 1; fi
      done
      echo "No package has too many versions."
    - |
      set -x # Installing govcms using ONLY our satis.
      cd workspace
      git checkout master
      composer config secure-http false # Only needed to point to local satis.
      # Different to default by adding /whitelist.
      cat composer.json | jq '.repositories'
      cat composer.json \
        | jq .repositories='{"govcms":{"type":"composer","url":"http://localhost:4680"},"whitelist":{"type":"composer","url":"http://localhost:4680/whitelist"},"packagist.org":false}' \
        | tee composer.json
      [ -s composer.json ] && echo "Why are you empty (Si debugging)."
      composer update
      composer validate
    - |
      set -x # Build the drupals.
      docker network prune -f && docker network create amazeeio-network
      docker login -u gitlab-ci-token -p $CI_JOB_TOKEN gitlab-registry-production.govcms.amazee.io
      docker-compose up -d mariadb
      docker-compose up -d cli
      docker-compose exec -T cli drush si -y govcms
    - |
      set -x # Test the drupals
      docker-compose exec -T cli drush status
    - |
      set -x # Test that we can now add a whitelist module.
      composer require drupal/migrate_plus ~4

before_script:
  - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
  - mkdir -p workspace
  - git clone --depth 1 --branch master https://github.com/govCMS/govcms8-scaffold-paas workspace
  - export DOCKER_HOST=tcp://localhost:2375
