---

image: quay.io/govcms/govcms-ci
variables:
  DOCKER_HOST: "tcp://localhost:2375"

services:
  - "docker:dind"

stages:
  - test

test:

  stage: test

  script:
    - mkdir -p workspace
    - cp tests/govcms-latest-composer.json workspace/composer.json
    - composer update -d workspace
    - composer verify -d workspace

before_script:
  - php -S localhost:4680 -t ./app > phpd.log 2>&1 &
