version: '2'

services:

  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      lagoon.type: nginx
      lagoon.deployment.strategy: Rolling
    volumes:
      - ./app:/app:delegated
    expose:
      - "8080"
    environment:
      LAGOON_LOCALDEV_URL: http://satis.docker.amazee.io

  # satis:
  #   Not needed as the container is only run on demand. See ahoy.

networks:
  amazeeio-network:
    external: true
