version: 2.1

jobs:
  build:
    docker:
      - image: composer/satis
    environment:
      SATIS: /satis/bin/satis
      SATIS_BUILD: /tmp/satis-build/app
    steps:
      - checkout
      - run:
          name: Build or prepare satis /app
          command: |
            # If satis build was automated, it would happen here. Currently just copy the committed /app to the build directory.
            mkdir -p "${SATIS_BUILD}"
            cp -R app/* "${SATIS_BUILD}"
      - persist_to_workspace:
          root: /tmp/satis-build
          paths:
            - .

  test:
    docker:
      - image: docker.io/govcms/govcms-ci
    environment:
      SATIS_BUILD: /tmp/satis-build/app
      GOVCMS_SCAFFOLD: /tmp/govcms-build
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/satis-build
      - run:
          name: Test that GovCMS can be built
          command: |
            # Get package versions required for testing stable release.
            VERSION_GOVCMS=$(cat ./satis-config/govcms-stable.json | jq -r '.require | .["govcms/govcms"]')
            VERSION_TOOLING=$(cat ./satis-config/govcms-stable.json | jq -r '.require | .["govcms/scaffold-tooling"]')
            VERSION_DEV=$(cat ./satis-config/govcms-stable.json | jq -r '.require | .["govcms/require-dev"]')

            echo "--> Starting satis web server on http://localhost:4141"
            php -S localhost:4141 -t "${SATIS_BUILD}" > /tmp/phpd.log 2>&1 &
            echo "--> Cloning govcms8-scaffold-paas into ${GOVCMS_SCAFFOLD}"
            composer create-project --no-install --quiet govcms/govcms8-scaffold-paas "${GOVCMS_SCAFFOLD}"
            cd "${GOVCMS_SCAFFOLD}"
            composer config secure-http false

            for branch in {"","develop","master"}; do
              echo
              echo "--> --------------------------------------------------------"
              echo "--> Test build GovCMS against http://localhost:4141/${branch}"
              echo

              rm -fR vendor && rm -f composer.lock
              composer config repositories.govcms composer http://localhost:4141/"${branch}"
              if [ "${branch}" = "master" ] || [ "${branch}" = "develop" ] ; then
                composer require --no-update \
                    govcms/govcms:1.x \
                    govcms/scaffold-tooling:dev-"${branch}" \
                    govcms/require-dev:dev-"${branch}" \
                    symfony/event-dispatcher:"v4.3.11 as v3.4.35" # @todo: remove once govcms/govcms no longer requires "symfony/event-dispatcher:v4.3.11 as v3.4.35" which only works at the root composer.json level.
              else
                echo -e "--> Expected stable versions, based on the satis config: \n     - govcms/govcms:${VERSION_GOVCMS} \n     - govcms/scaffold-tooling:${VERSION_TOOLING} \n     - govcms/require-dev:${VERSION_DEV}"
                composer require --no-update \
                    govcms/govcms:"${VERSION_GOVCMS}" \
                    govcms/scaffold-tooling:"${VERSION_TOOLING}" \
                    govcms/require-dev:"${VERSION_DEV}" \
                    symfony/event-dispatcher:"v4.3.11 as v3.4.35" # @todo: remove once govcms/govcms no longer requires "symfony/event-dispatcher:v4.3.11 as v3.4.35" which only works at the root composer.json level.
              fi
              cat composer.json | jq .require
              composer -n --quiet --no-suggest --no-scripts update
              composer info | grep ^govcms
            done


workflows:
  version: 2.1
  update:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
      - test:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build
