version: 2
jobs:
  test:
    docker:
      - image: quay.io/govcms/govcms-ci
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Require one package per project
          command: |
            echo "Be on upstream_changes branch"
            echo "Merge master"
            ahoy build-all-production
            echo "Commit yo"

workflows:
  version: 2
  main:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
  upstream_trigger:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
            branches:
              ignore: /.*/
