version: 2.1

jobs:
  test: &job-test
    docker:
      - image: docker.io/govcms/govcms-ci
    steps:
      - checkout
      - run: ./.circleci/test.sh

  test_master:
    <<: *job-test
    environment:
      SATIS_BRANCH: master

  test_develop:
    <<: *job-test
    environment:
      SATIS_BRANCH: develop


workflows:
  version: 2.1
  update:
    jobs:
      - test
      - test_master
      - test_develop
